### ISSUE TITLE
change drain to be consistent with `Vec`

### ISSUE THREAD

**Issue by lcnr** [servo/rust-smallvec#142]
`drain` has a different signature than `Vec`, in case this is something that is worth fixing, I would be glad to post a PR.

SmallVec: `pub fn drain(&mut self) -> Drain<A::Item>`
Vec: `pub fn drain<R>(&mut self, range: R) -> Drain<T>
        where R: RangeBounds<usize>`

**Comment by mbrubeck** [comment]
This will only work on Rust 1.28 and later, because `RangeBounds` was not stable in earlier versions.  (The current version of smallvec is compatible with Rust 1.20.)

I think we should release a new major version of smallvec soon that increases the Rust version requirement, along with making some of the other breaking changes listed in #73.  If you'd like to submit a PR for this issue, we can include it in that release.

**Comment by lcnr** [comment]
This seems far more complicated than expected, as drain might leave the `0..start` might be smaller than `inline_size` which causes problem as the union might suddenly get misinterpreted. While I think that I have a safe solution, it will take a few more days until it's finished.
