### ISSUE TITLE
`SmallVec::insert_many` is unsound

### ISSUE THREAD

**Issue by Vurich** [servo/rust-smallvec#96]
[Gist here](https://gist.github.com/Vurich/ffa55d8e69377a64c9708e07c2db2a1b). A solution to this would be to set `len = index` before iterating. Obviously this would cause leaks but we're already leaking data.

(Sorry for the very verbose explanation in the linked gist but I wanted to link it as part of an article whose audience might not immediately understand the problem).

**Comment by mbrubeck** [comment]
Good catch.  The proposed solution sounds good to me.

**Comment by Shnatsel** [comment]
Double free is an [exploitable security vulnerability](https://heap-exploitation.dhavalkapil.com/attacks/double_free.html). Once the fix is released, please add this issue to the [Rust security advisory database](https://github.com/RustSec/advisory-db).

I would also urge you to publish a fixed version ASAP. Despite the fact that the double free only happens on panic, this bug still can be exploited in a multi-threaded application that catches panics.

**Comment by mbrubeck** [comment]
Submitted a fix in #103.

**Comment by mbrubeck** [comment]
RustSec/advisory-db#30

**Comment by Shnatsel** [comment]
Would you consider [yanking](https://doc.rust-lang.org/cargo/reference/publishing.html#managing-a-cratesio-based-crate) vulnerable versions from crates.io? 

Existing dependencies on them will continue to work, but people won't be able to make new crates depending on vulnerable versions by following e.g. a tutorial that was not updated following this advisory.
